---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t ksslab-devops-image:latest .
    args:
      chdir: /opt/k8kslab

  - name: create tag to image
    command: docker tag ksslab-devops-image mujeebks10/ksslab-devops-image

  - name: push image on to dockerhub
    command: docker push mujeebks10/ksslab-devops-image

  - name: remove docker images form ansible server
    command: docker rmi ksslab-devops-image:latest mujeebks10/ksslab-devops-image
    ignore_errors: yes
